# inventory/hosts.yml
---
all:
  children:
    gns3_servers:
      hosts:
        gns3_vm:
          ansible_host: 192.168.238.128
          ansible_user: gns3
          ansible_ssh_pass: gns3
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python
          gns3_url: "http://192.168.238.128:80"
      vars:
        gns3_project_name: "ansible_network"