[gns3_servers]
gns3_vm ansible_host=192.168.238.128

[gns3_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_connection=ssh
ansible_user=gns3
ansible_ssh_pass=gns3
ansible_become=yes
ansible_become_method=sudo
ansible_become_ask_pass=no