---
all:
  children:
    gns3_servers:
      hosts:
        gns3_vm:
          ansible_host: 192.168.238.128
          ansible_user: gns3
          ansible_ssh_pass: gns3
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: gns3
      vars:
        gns3_url: "http://{{ ansible_host }}"
        gns3_port: 80
        gns3_project_name: "ansible_test_network_v15"