---
  - name: Deploy GNS3 Network
    hosts: gns3_servers
    gather_facts: no
    vars:
      gns3_url: "http://192.168.238.128"
      gns3_port: 80
      gns3_project_name: "ansible_test_network"
      project_config:
        name: "{{ gns3_project_name }}"
        auto_close: true
        auto_open: false
        auto_start: false
        drawing_grid_size: 25
        grid_size: 75
        scene_height: 1000
        scene_width: 2000
        show_grid: false
        show_interface_labels: false
        snap_to_grid: false
        zoom: 100
    
    tasks:
      - name: Create GNS3 project
        uri:
          url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects"
          method: POST
          body_format: json
          body: "{{ project_config }}"
          status_code: [200, 201]
        register: project_result
  
      - name: Display project details
        debug:
          var: project_result.json
  
      - name: Save project ID for future use
        set_fact:
          project_id: "{{ project_result.json.project_id }}"
  
      - name: Verify project status
        uri:
          url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}"
          method: GET
          status_code: 200
        register: project_status
  
      - name: Display project status
        debug:
          var: project_status.json