---
- name: Deploy GNS3 Network with Cisco Routers
  hosts: gns3_servers
  gather_facts: no
  vars:
    gns3_url: "http://192.168.238.128"
    gns3_port: 80
    gns3_project_name: "ansible_test_network_10"
    cisco_template_name: "Cisco 7200"
    cisco_image_name: "c7200-adventerprisek9-mz.153-3.XB12.image"
    cisco_image_path: "/home/gns3/GNS3/images/IOS"  # Update this path
    project_config:
      name: "{{ gns3_project_name }}"
      auto_close: true
      auto_open: false
      auto_start: false
      drawing_grid_size: 25
      grid_size: 75
      scene_height: 1000
      scene_width: 2000
      show_grid: false
      show_interface_labels: false
      snap_to_grid: false
      zoom: 100
  tasks:
    - name: Get GNS3 version
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/version"
        method: GET
      register: gns3_version

    - name: Display GNS3 version
      debug:
        var: gns3_version.json

    - name: Create GNS3 project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects"
        method: POST
        body_format: json
        body: "{{ project_config }}"
        status_code: [200, 201]
      register: project_result

    - name: Save project ID
      set_fact:
        project_id: "{{ project_result.json.project_id }}"

    - name: Get Cisco 7200 template details
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/templates"
        method: GET
        status_code: 200
      register: templates_result

    - name: Find Cisco 7200 template ID
      set_fact:
        cisco_template_id: "{{ item.template_id }}"
      loop: "{{ templates_result.json }}"
      when: item.name == cisco_template_name

    - name: Set router coordinates
      set_fact:
        router_coords:
          - { name: "R1", x: 100, y: 0 }
          - { name: "R2", x: 200, y: 0 }

    - name: Deploy Cisco 7200 routers
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/templates/{{ cisco_template_id }}"
        method: POST
        body_format: json
        body: "{{ {'name': item.name, 'x': item.x|int, 'y': item.y|int} | to_json }}"
        status_code: 201
      loop: "{{ router_coords }}"
      register: router_results

    - name: Start the project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/open"
        method: POST
        status_code: [200, 201]
      register: start_result

    - name: Display start project result
      debug:
        var: start_result

    - name: Verify project is running
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}"
        method: GET
        status_code: 200
      register: final_project_status

    - name: Display final project status
      debug:
        var: final_project_status.json

    - name: Project deployment summary
      debug:
        msg: |
          GNS3 Project Deployment Summary:
          - Project Name: {{ gns3_project_name }}
          - Project ID: {{ project_id }}
          - Routers Deployed: {{ router_coords | length }}
          - Project Status: {{ final_project_status.json.status }}