---
- name: Deploy GNS3 Network with Cisco Routers
  hosts: gns3_servers
  gather_facts: no
  vars_files:
    - ../group_vars/all.yaml

  tasks:
    - name: Get GNS3 version
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/version"
        method: GET
      register: gns3_version

    - name: Display GNS3 version
      debug:
        var: gns3_version.json

    - name: Create GNS3 project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects"
        method: POST
        body_format: json
        body: "{{ project_config }}"
        status_code: [200, 201]
      register: project_result

    - name: Save project ID
      set_fact:
        project_id: "{{ project_result.json.project_id }}"

    - name: Get Cisco 7200 template details
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/templates"
        method: GET
        status_code: 200
      register: templates_result

    - name: Find Cisco 7200 template ID
      set_fact:
        cisco_template_id: "{{ item.template_id }}"
      loop: "{{ templates_result.json }}"
      when: item.name == cisco_template_name

    - name: Deploy Cisco 7200 routers
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/templates/{{ cisco_template_id }}"
        method: POST
        body_format: json
        body: "{{ {'name': item.name, 'x': item.x|int, 'y': item.y|int} | to_json }}"
        status_code: 201
      loop: "{{ router_coords }}"
      register: router_results

    - name: Start the project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/open"
        method: POST
        status_code: [200, 201]
      register: start_result

    - name: Display start project result
      debug:
        var: start_result

    - name: Verify project is running
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}"
        method: GET
        status_code: 200
      register: final_project_status

    - name: Display final project status
      debug:
        var: final_project_status.json

    - name: Project deployment summary
      debug:
        msg: |
          GNS3 Project Deployment Summary:
          - Project Name: {{ gns3_project_name }}
          - Project ID: {{ project_id }}
          - Routers Deployed: {{ router_coords | length }}
          - Project Status: {{ final_project_status.json.status }}