---
- name: Deploy Spine-Leaf Architecture in GNS3
  hosts: gns3_servers
  gather_facts: no
  vars_files:
    - ../group_vars/all.yaml

  tasks:
    - name: Create GNS3 project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects"
        method: POST
        body_format: json
        body: "{{ project_config | to_json }}"
        status_code: [201, 409]
      register: project_result

    - name: Set project ID
      set_fact:
        project_id: "{{ project_result.json.project_id }}"

    - name: Get existing templates
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/templates"
        method: GET
      register: existing_templates

    - name: Create Cisco 7200 template if it doesn't exist
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/templates"
        method: POST
        body_format: json
        body: 
          name: "{{ cisco_7200_template_name }}"
          compute_id: "local"
          template_type: "dynamips"
          image: "{{ cisco_7200_image_path }}/{{ cisco_7200_image_name }}"
          symbol: ":/symbols/router.svg"
          category: "router"
          ram: 512
          nvram: 128
        status_code: [200, 201, 409]
      when: cisco_7200_template_name not in (existing_templates.json | map(attribute='name') | list)

    - name: Create Cisco IOSvL2 template if it doesn't exist
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/templates"
        method: POST
        body_format: json
        body: 
          name: "{{ cisco_iosvl2_template_name }}"
          compute_id: "local"
          template_type: "qemu"
          hda_disk_image: "{{ cisco_iosvl2_image_path }}/{{ cisco_iosvl2_image_name }}"
          symbol: ":/symbols/multilayer_switch.svg"
          category: "switch"
          adapters: 16
          ram: 768
          console_type: "telnet"
          qemu_path: "{{ qemu_path }}"
          platform: "x86_64"
        status_code: [200, 201, 409]
      when: cisco_iosvl2_template_name not in (existing_templates.json | map(attribute='name') | list)

    - name: Get updated template list
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/templates"
        method: GET
      register: updated_templates

    - name: Find C7200 template IDs
      set_fact:
        cisco_7200_template_id: "{{ item.template_id }}"
      loop: "{{ updated_templates.json }}"
      when: item.name == cisco_7200_template_name

    - name: Find IOSvL2 template ID
      set_fact:
        cisco_iosvl2_template_id: "{{ item.template_id }}"
      loop: "{{ updated_templates.json }}"
      when: item.name == cisco_iosvl2_template_name

    - name: Deploy devices
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/templates/{% if item.template == cisco_7200_template_name %}{{ cisco_7200_template_id }}{% else %}{{ cisco_iosvl2_template_id }}{% endif %}"
        method: POST
        body_format: json
        body: "{{ {'name': item.name, 'x': item.x|int, 'y': item.y|int} | to_json }}"
        status_code: [201, 409]
      loop: "{{ devices }}"

    - name: Deploy VPCS nodes
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/nodes"
        method: POST
        body_format: json
        body: "{{ {'name': item.name, 'node_type': 'vpcs', 'compute_id': 'local', 'x': item.x|int, 'y': item.y|int} | to_json }}"
        status_code: 201
      loop: "{{ vpcs_nodes }}"

    - name: Get all nodes in the project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/nodes"
        method: GET
      register: all_nodes

    - name: Create device ID map
      set_fact:
        device_id_map: "{{ device_id_map | default({}) | combine({item.name: item.node_id}) }}"
      loop: "{{ all_nodes.json }}"

    - name: Get detailed information for each node
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/nodes/{{ item.node_id }}"
        method: GET
      loop: "{{ all_nodes.json }}"
      register: node_details

    - name: Create port mapping for each device
      set_fact:
        port_map: "{{ port_map | default({}) | combine({item.json.name: item.json.ports | map(attribute='port_number') | map('int') | list}) }}"
        adapter_map: "{{ adapter_map | default({}) | combine({item.json.name: item.json.ports | map(attribute='adapter_number') | map('int') | list}) }}"
      loop: "{{ node_details.results }}"

    - name: Configure additional interfaces on Core routers
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/nodes/{{ device_id_map[item] }}"
        method: PUT
        body_format: json
        body:
          properties:
            slot1: PA-FE-TX
            slot2: PA-FE-TX
        status_code: [200, 201, 204]
      loop:
        - Core1
        - Core2

    - name: Reload Core routers
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/nodes/{{ device_id_map[item] }}/reload"
        method: POST
        status_code: [200, 201, 204]
      loop:
        - Core1
        - Core2

    - name: Wait for Core routers to come back online
      wait_for:
        timeout: 60

    - name: Get updated node information
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/nodes/{{ device_id_map[item] }}"
        method: GET
      loop:
        - Core1
        - Core2
      register: updated_core_info
    
    - name: Update port and adapter maps for Core routers
      set_fact:
        port_map: "{{ port_map | combine({item.json.name: item.json.ports | map(attribute='port_number') | map('int') | list}) }}"
        adapter_map: "{{ adapter_map | combine({item.json.name: item.json.ports | map(attribute='adapter_number') | map('int') | list}) }}"
      loop: "{{ updated_core_info.results }}"

    - name: Create links between devices
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/links"
        method: POST
        body_format: json
        body: >
          {
            "nodes": [
              {
                "node_id": "{{ device_id_map[item.node_a] }}",
                "adapter_number": {% if 'Core' in item.node_a %}{{ item.port_a | int }}{% else %}{{ adapter_map[item.node_a][item.port_a | int] | default(0) }}{% endif %},
                "port_number": {% if 'Core' in item.node_a %}0{% else %}{{ port_map[item.node_a][item.port_a | int] | default(item.port_a) }}{% endif %}
              },
              {
                "node_id": "{{ device_id_map[item.node_b] }}",
                "adapter_number": {% if 'Core' in item.node_b %}{{ item.port_b | int }}{% else %}{{ adapter_map[item.node_b][item.port_b | int] | default(0) }}{% endif %},
                "port_number": {% if 'Core' in item.node_b %}0{% else %}{{ port_map[item.node_b][item.port_b | int] | default(item.port_b) }}{% endif %}
              }
            ]
          }
        status_code: [201, 409]
      loop: "{{ links }}"

    - name: Start the project
      uri:
        url: "{{ gns3_url }}:{{ gns3_port }}/v2/projects/{{ project_id }}/open"
        method: POST
        status_code: [200, 201]