# playbooks/test_module.yml
---
- name: Test GNS3 Module
  hosts: gns3_servers
  gather_facts: no
  
  tasks:
    - name: List available modules
      shell: ansible-doc -l | grep gns3
      register: modules
      changed_when: false
      delegate_to: localhost
      ignore_errors: yes

    - name: Check GNS3 collection installation
      command: ansible-galaxy collection list davidban77.gns3
      register: collection_check
      changed_when: false
      delegate_to: localhost
      ignore_errors: yes

    - name: Display collection status
      debug:
        var: collection_check

    - name: Test GNS3 API connection
      uri:
        url: "{{ gns3_url }}/v2/version"
        method: GET
      register: api_result
      ignore_errors: yes

    - name: Display GNS3 API result
      debug:
        var: api_result