---
- name: Deploy GNS3 Network
  hosts: gns3_servers
  gather_facts: no
  
  vars:
    gns3_url: "http://192.168.238.128:80"
    gns3_project_name: "ansible_test_network"
  
  tasks:
    - name: Debug - Print Python path
      command: which python3
      register: python_path
      
    - name: Debug - Print Python version
      command: python3 --version
      register: python_version
      
    - name: Debug - Display results
      debug:
        msg: 
          - "Python Path: {{ python_path.stdout }}"
          - "Python Version: {{ python_version.stdout }}"
    
    - name: Install required Python packages
      pip:
        name: 
          - gns3fy
          - requests
        state: present
      
    - name: Debug - Verify gns3fy installation
      command: python3 -c "import gns3fy; print(gns3fy.__version__)"
      register: gns3fy_version
      
    - name: Debug - Display gns3fy version
      debug:
        msg: "GNS3fy Version: {{ gns3fy_version.stdout }}"
    
    - name: Create network topology
      davidban77.gns3.gns3_project:
        url: "{{ gns3_url }}"
        project_name: "{{ gns3_project_name }}"
        state: present
      register: project
    
    - name: Display project details
      debug:
        var: project